service: resgatar-community

frameworkVersion: "3"

custom:
  environment: ${file(./config/${self:provider.stage}.json):environment}
  esbuild: ${file(esbuild.config.js)}

provider:
  name: aws
  runtime: nodejs20.x
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'hml'}
  environment:
    STAGE: ${self:provider.stage}
    SERVICE_NAME: ${self:custom.environment.SERVICE}
    USER_POOL_ID: ${self:custom.environment.USER_POOL_ID}
    CLIENT_ID: ${self:custom.environment.CLIENT_ID}
    DB: ${self:custom.environment.DB}

  httpApi:
    authorizers:
      cognitoAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: ${self:custom.environment.COGNITO_URL}
        audience:
          - ${self:custom.environment.CLIENT_ID}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - cognito-idp:AdminCreateUser
        - cognito-idp:AdminInitiateAuth
        - cognito-idp:AdminSetUserPassword
        - cognito-idp:AdminRespondToAuthChallenge
        - cognito-idp:AdminGetUser
        - cognito-idp:ListUsers
      Resource:
        - ${self:custom.environment.COGNITO_USER_POOL_ARN}

plugins:
  - serverless-esbuild

functions:
  signup:
    handler: src/handler/members/signup.execute
    events:
      - httpApi:
          path: /signup
          method: POST
          authorizer:
            name: cognitoAuthorizer
