service: resgatar-community

frameworkVersion: "3"

custom:
  environment: ${file(./config/${self:provider.stage}.json):environment}
  esbuild: ${file(esbuild.config.js)}

provider:
  name: aws
  runtime: nodejs20.x
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'hml'}
  environment:
    STAGE: ${self:provider.stage}
    SERVICE_NAME: ${self:custom.environment.SERVICE}

  httpApi:
    authorizers:
      cognitoAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: ${self:custom.environment.COGNITO_URL}
        audience:
          - ${self:custom.environment.CLIENT_ID}

plugins:
  - serverless-esbuild

functions:
  hello:
    handler: src/handler.hello
    events:
      - httpApi:
          path: /hello
          method: get
          authorizer:
            name: cognitoAuthorizer
